CREATE TABLE IF NOT EXISTS utilisateur (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     nom VARCHAR(100) NOT NULL,
     prenom VARCHAR(100) NOT NULL,
     adresse VARCHAR(255),
     password VARCHAR(255) NOT NULL,
     email VARCHAR(150) NOT NULL UNIQUE
)ENGINE=InnoDB;

