server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_history_utilisateur
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

jwt:
  secret: food123456789app123456789food123456789app123456789
  expiration: 86400000